### ISSUE TITLE
Sorry, please ignore [A11 support]

### ISSUE THREAD

**Issue by bushrang3r** [veniosg/SwissArmySearch#31]
Sorry, my bad. It does support A11.

I'm just wondering if there are any plans to support Android 11.

Thanks.

**Comment by veniosg** [comment]
No worries. Btw I'm not sure what you mean by A11 if not Android 11, but I don't think that version's changes should affect Just Search so I'd expect it to work the same :)

**Comment by bushrang3r** [comment]
Yes, I meant Android 11.
Thank you sir! 🙂
